tracker_index:
    pattern: /tracker
    defaults: { _controller: "GitonomyTicketingBundle:Tracker:index" }

tracker_create:
    pattern: /tracker/create
    defaults: { _controller: "GitonomyTicketingBundle:Tracker:create" }

tracker_update:
    pattern: /tracker/edit/{id}
    defaults: { _controller: "GitonomyTicketingBundle:Tracker:edit" }

tracker_delete:
    pattern: /tracker/delete/{id}
    defaults: { _controller: "GitonomyTicketingBundle:Tracker:delete" }