tracker_index:
    pattern: /tracker
    defaults: { _controller: "GitonomyTicketingBundle:TicketTracker:index" }

tracker_create:
    pattern: /tracker/create
    defaults: { _controller: "GitonomyTicketingBundle:TicketTracker:create" }

tracker_update:
    pattern: /tracker/edit/{id}
    defaults: { _controller: "GitonomyTicketingBundle:TicketTracker:edit" }

tracker_delete:
    pattern: /tracker/delete/{id}
    defaults: { _controller: "GitonomyTicketingBundle:TicketTracker:delete" }